BEGIN TRANSACTION;

CREATE TABLE gauge(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    value DOUBLE PRECISION NOT NULL
);

CREATE TABLE counter(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    value BIGINT NOT NULL
);

COMMIT;